### PR TITLE
Flybits url

### PR DESCRIPTION
**Pull request by jkyjustin**
### Checklist

  - [ ] PR title is clear and describes the work
  - [ ] Commit messages are self-explanatory and summarize the change
  - [ ] Unit tests are provided for the new change

### CODE REVIEW

**Comment by jkyjustin** [comment]
oops

**Comment by moorara** [comment]
@jkyjustin Hey Justin, nice to see you here 😉
I guess you also need to make sure the `update` command for Cherry is downloading from flybits url.
https://github.com/moorara/cherry/blob/v0.4.4/internal/action/update.go#L15

**Comment by jkyjustin** [comment]
@moorara Milad! I texted you yesterday apologizing for the disturbance in your repo, did you change your number or something?

Thanks for the heads up and hope all is going well.

**Comment by moorara** [comment]
@jkyjustin sorry, I contacted you 😉

**Pull request closed without merging**
